[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
port = 8080
headless = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8080
